### ISSUE TITLE
Implement `assert_return_*_nan_*`

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wat#23]
I see that in https://github.com/WAVM/WAVM/issues/187 they have switched the `assert_return_canonical_nan` and `assert_return_arithmetic_nan` to support a type parameter for `v128`s. It looks like two different styles are discussed there:
 - `(assert_return_canonical_nan (invoke ...) f32x4)`
 - `(assert_return_canonical_nan_f32x4 (invoke ...))`

We should pick one of these and add it to `ast/wast.rs`; it looks like the comments in https://github.com/WAVM/WAVM/issues/187 lean towards the former but I do see that @Honry used the latter in https://github.com/WebAssembly/simd/blob/master/test/core/simd/simd_f32x4.wast#L994 and following.

**Comment by alexcrichton** [comment]
Sounds reasonable to me! I'd be down for a PR to add these variants.

**Comment by alexcrichton** [comment]
Added in https://github.com/bytecodealliance/wat/pull/33
