### ISSUE TITLE
atomic.fence is missing memory order immediate

### ISSUE THREAD

**Issue by eqrion** [bytecodealliance/wat#59]
See binary format in [1]. There's a reserved single byte for a memory order argument for `atomic.fence`. It's not specifiable in the text format.

[1] https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md

**Comment by alexcrichton** [comment]
Oh dear, this is what happens when 99% of your tests are against another tool (in this case wabt) and then this implements more features than that tool! Thanks for the report though!

**Comment by eqrion** [comment]
Thanks for the quick fix!
