### ISSUE TITLE
Implement the GC proposal

### ISSUE THREAD

**Issue by eqrion** [bytecodealliance/wat#64]
I've now gotten `wat` integrated and [passing our test suite](https://bugzilla.mozilla.org/show_bug.cgi?id=1612534#c4) in SpiderMonkey. Thanks for the quick resolution of issues!

The remaining blocker to landing this is to support the experimental GC syntax. I'm not sure what the canonical documentation for this is. It's either our implementation, [Lars' documentation](https://github.com/lars-t-hansen/moz-gc-experiments), or the GC repo. @lars-t-hansen do you know?

I'm happy to implement this, just wanted to provide a heads up.

**Comment by lars-t-hansen** [comment]
Since people are depending on the syntax we support in SpiderMonkey, using my documentation (which should be effectively identical to what we implement) is best for the time being.  This can be allowed to change over time, but the GC proposal is very slow moving and in a very early stage, and it's best to duplicate what we have for now.

**Comment by alexcrichton** [comment]
Sounds good to me! If you need any pointers @eqrion just lemme know, happy to help out around the code.

In terms of tests almost all tests right now are reference checks against wabt, and I don't think wabt implements the GC proposal. In that sense if you add `*.wat` or `*.wast` files the test suite will ensure that they parse and generate a binary, but basically just without panics.

If you want to specifically test the binary encoding that'll be  a bit harder, but it's fine to not have tests for that.

**Comment by lars-t-hansen** [comment]
Ben Smith just posted a WIP PR for GC support in Wabt: https://github.com/WebAssembly/wabt/pull/1345

**Comment by alexcrichton** [comment]
Oh nice, excellent timing :)
