### ISSUE TITLE
Getting encoded offsets of function bodies

### ISSUE THREAD

**Issue by eqrion** [bytecodealliance/wat#69]
I thought this was unused in SpiderMonkey, but found out that we likely do need it.

If you pass an optional flag to our text to binary function, we return the encoded module along with a list of offsets to the start of each function body. This is used for some debugger tests to place breakpoints on functions.

It's possible that we could decode the binary and find these after it has been encoded. If it's easy to add to wat (or more likely wast), then that may be a nicer option for us.

[1] https://searchfox.org/mozilla-central/rev/f36cb2af46edd2659f446b7acdb2154e230ee445/js/src/wasm/WasmTextToBinary.cpp#7174

**Comment by alexcrichton** [comment]
Sounds reasonable to me! I think it'd make sense to [change the return value here](https://github.com/bytecodealliance/wat/blob/4406bcfb1189504537ef0aef3249cfe837a1c51a/crates/wast/src/ast/module.rs#L111-L114) to something like an opaque `EncodedModule`. You could pull out the `&[u8]` from that and we'd also be able to add tables like here for "where did this encoded item start". Eventually we could return other metadata as well if necessary.

**Comment by eqrion** [comment]
On second thought, all the tests that I'm seeing compile the bytecode to a Module before needing the offsets. I think we could add a test-only method on Module to get bytecode offsets for functions and that would be cleaner. Will try this first.

**Comment by eqrion** [comment]
So I couldn't read code correctly apparently. The metadata needed is the offset of every instruction inside the code section. Except the implementation seems incomplete and only reports instructions that were not defined with nested S-exprs.

This code really isn't used much, my patch to implement this in `wat` ballooned to be a very large change, and I can't think of anyone else who would benefit from it.

So I've now wrote a tiny function using wasmparser to get what we need and exposed that as a testing function and it works. Closing this now.

**Comment by eqrion** [comment]
Oh, forgot to add that it would be useful to get a new release then!

**Comment by alexcrichton** [comment]
Ok published new versions!

**Comment by eqrion** [comment]
Thanks!
