### ISSUE TITLE
Align GC syntax and encoding with WABT

### ISSUE THREAD

**Issue by eqrion** [bytecodealliance/wat#72]
V8 and WABT are implementing a subset of the GC proposal deemed the MVA. I believe we will be compliant on the text syntax front, as that's well documented in the MVP.md doc. The encodings aren't specified that I'm aware of, so that will need to be aligned.

[1] https://github.com/WebAssembly/gc/issues/81

**Comment by alexcrichton** [comment]
FWIW I updated the wabt submodule and [added a directive to ignore wabt's gc tests](https://github.com/bytecodealliance/wat/blob/ea677287d61200ae312e7d023a28530b517d278e/tests/wabt.rs#L495-L498), so once that's removed it'll show what's left to get things at least mostly compatible.
