### ISSUE TITLE
wat encodes non-existent operations

### ISSUE THREAD

**Issue by lars-t-hansen** [bytecodealliance/wat#82]
From what I can tell, these:

`i64x2.all_true` and `i64x2.any_true`: https://github.com/bytecodealliance/wat/blob/master/crates/wast/src/ast/expr.rs#L815.  

`i8x16.mul`: https://github.com/bytecodealliance/wat/blob/master/crates/wast/src/ast/expr.rs#L776

They have been removed from the spec and there's no reason to suggest they're coming back.

**Comment by alexcrichton** [comment]
Ah yeah I haven't been tracking spec removals very well, but seems fine to delete whenever!
